INSERT INTO instruments (instrument_id, ticker, name) VALUES 
(-1, 'CASH', 'CASH'),
(1, 'ADBE', 'Adobe'),
(2, 'AMZN', 'Amazon'),
(3, 'AMD', 'AMD'),
(4, 'AAPL', 'Apple'),
(5, 'CVX', 'Chevron'),
(6, 'LLY', 'Eli Lilly'),
(7, 'HD', 'The Home Depot'),
(8, 'JNJ', 'Johnson & Johnson'),
(9, 'MA', 'Mastercard'),
(10, 'MCD', 'McDonalds'),
(11, 'META', 'Meta'),
(12, 'MSFT', 'Microsoft'),
(13, 'NVDA', 'Nvidia'),
(14, 'PG', 'Procter & Gamble'),
(15, 'TSLA', 'Tesla'),
(16, 'V', 'Visa'),
(17, 'WMT', 'Walmart')