INSERT INTO instrument_metadata (instrument_id, display_name, sector, icon_path, synopsis)
VALUES
(-1, 'Cash', 'Cash', '/icons/cash.svg', 'Cash'),

(1, 'Adobe Inc.', 'Information Technology', '/icons/companies/grey/adobe.svg', 'Adobe Inc. (/əˈdoʊbi/ ə-DOH-bee), originally called Adobe Systems Incorporated, is an American multinational computer software company incorporated in Delaware and headquartered in San Jose, California. It has historically specialized in software for the creation and publication of a wide range of content, including graphics, photography, illustration, animation, multimedia/video, motion pictures, and print. Its flagship products include Adobe Photoshop image editing software; Adobe Illustrator vector-based illustration software; Adobe Acrobat Reader and the Portable Document Format (PDF); and a host of tools primarily for audio-visual content creation, editing and publishing. Adobe offered a bundled solution of its products named Adobe Creative Suite, which evolved into a subscription software as a service (SaaS) offering named Adobe Creative Cloud. The company also expanded into digital marketing software and in 2021 was considered one of the top global leaders in Customer Experience Management (CXM).

Adobe was founded in December 1982 by John Warnock and Charles Geschke, who established the company after leaving Xerox PARC to develop and sell the PostScript page description language. In 1985, Apple Computer licensed PostScript for use in its LaserWriter printers, which helped spark the desktop publishing revolution. Adobe later developed animation and multimedia through its acquisition of Macromedia, from which it acquired Macromedia Flash; video editing and compositing software with Adobe Premiere, later known as Adobe Premiere Pro; low-code web development with Adobe Muse; and a suite of software for digital marketing management.

As of 2022, Adobe has more than 26,000 employees worldwide. Adobe also has major development operations in the United States in Newton, New York City, Arden Hills, Lehi, Seattle, Austin and San Francisco. It also has major development operations in Noida and Bangalore in India. '
),

(2, 'Amazon.com, Inc.', 'Retail', '/icons/companies/grey/amazon.svg', 'Amazon.com, Inc. (/ˈæməzɒn/ AM-ə-zon UK also /ˈæməzən/ AM-ə-zən) is an American multinational technology company focusing on e-commerce, cloud computing, online advertising, digital streaming, and artificial intelligence. It has been often referred to as "one of the most influential economic and cultural forces in the world", and is often regarded as one of the world’s most valuable brands. It is considered as one of the Big Five American technology companies, alongside Alphabet (parent company of Google), Apple, Meta (formerly Facebook Inc.) and Microsoft.

Amazon was founded by Jeff Bezos from his garage in Bellevue, Washington, on July 5, 1994. Initially an online marketplace for books, it has expanded into a multitude of product categories, a strategy that has earned it the moniker The Everything Store. It has multiple subsidiaries including Amazon Web Services (cloud computing), Zoox (autonomous vehicles), Kuiper Systems (satellite Internet), and Amazon Lab126 (computer hardware R&D). Its other subsidiaries include Ring, Twitch, IMDb, and Whole Foods Market. Its acquisition of Whole Foods in August 2017 for US$13.4 billion substantially increased its footprint as a physical retailer.

Amazon has earned a reputation as a disruptor of well-established industries through technological innovation and "aggressive" reinvestment of profits into capital expenditures. As of 2023, it is the world’s largest online retailer and marketplace, smart speaker provider, cloud computing service through AWS, live-streaming service through Twitch, and Internet company as measured by revenue and market share. In 2021, it surpassed Walmart as the world’s largest retailer outside of China, driven in large part by its paid subscription plan, Amazon Prime, which has over 200 million subscribers worldwide. It is the second-largest private employer in the United States.

Amazon also distributes a variety of downloadable and streaming content through its Amazon Prime Video, Amazon Music, Twitch, and Audible units. It publishes books through its publishing arm, Amazon Publishing, film and television content through Amazon Studios, and has been the owner of film and television studio Metro-Goldwyn-Mayer since March 2022. It also produces consumer electronics—most notably, Kindle e-readers, Echo devices, Fire tablets, and Fire TVs.

Amazon has been criticized for customer data collection practices, a toxic work culture, tax avoidance, and anti-competitive behavior. 
'),

(3, 'Advanced Micro Devices, Inc.', 'Information Technology', '/icons/companies/grey/amd.svg', 'Advanced Micro Devices, Inc., commonly abbreviated as AMD, is an American multinational semiconductor company based in Santa Clara, California, that develops computer processors and related technologies for business and consumer markets.

The company was founded in 1969 by Jerry Sanders and a group of other technology professionals. AMD’s early products were primarily memory chips and other components for computers. The company later expanded into the microprocessor market, competing with Intel, its main rival in the industry. In the early 2000s, AMD experienced significant growth and success, thanks in part to its strong position in the PC market and the success of its Athlon and Opteron processors. However, the company faced challenges in the late 2000s and early 2010s, as it struggled to keep up with Intel in the race to produce faster and more powerful processors. In the late 2010s, AMD regained some of its market share thanks to the success of its Ryzen processors which are now widely regarded as superior to Intel products in business applications including cloud applications. AMD’s processors are used in a wide range of computing devices, including personal computers, servers, laptops, and gaming consoles. While it initially manufactured its own processors, the company later outsourced its manufacturing, a practice known as going fabless, after GlobalFoundries was spun off in 2009.

AMD’s main products include microprocessors, motherboard chipsets, embedded processors, graphics processors, and FPGAs for servers, workstations, personal computers, and embedded system applications. The company has also expanded into new markets, such as the data center and gaming markets, and has announced plans to enter the high-performance computing market. 
'),

(4, 'Apple Computer Inc.', 'Information Technology', '/icons/companies/grey/apple.svg', 'Apple Inc. is an American multinational technology company headquartered in Cupertino, California. Apple is the world’s largest technology company by revenue, with US$394.3 billion in 2022 revenue. As of March 2023, Apple is the world’s biggest company by market capitalization. As of June 2022, Apple is the fourth-largest personal computer vendor by unit sales and the second-largest mobile phone manufacturer in the world. It is one of the Big Five American information technology companies, alongside Alphabet, Amazon, Meta Platforms, and Microsoft.

Apple was founded as Apple Computer Company on April 1, 1976, by Steve Wozniak, Steve Jobs and Ronald Wayne to develop and sell Wozniak’s Apple I personal computer. It was incorporated by Jobs and Wozniak as Apple Computer, Inc. in 1977. The company’s second computer, the Apple II, became a best seller and one of the first mass-produced microcomputers. Apple went public in 1980 to instant financial success. The company developed computers featuring innovative graphical user interfaces, including the 1984 original Macintosh, announced that year in a critically acclaimed advertisement called "1984". By 1985, the high cost of its products, and power struggles between executives, caused problems. Wozniak stepped back from Apple and pursued other ventures, while Jobs resigned and founded NeXT, taking some Apple employees with him.

As the market for personal computers expanded and evolved throughout the 1990s, Apple lost considerable market share to the lower-priced duopoly of the Microsoft Windows operating system on Intel-powered PC clones (also known as "Wintel"). In 1997, weeks away from bankruptcy, the company bought NeXT to resolve Apple’s unsuccessful operating system strategy and entice Jobs back to the company. Over the next decade, Jobs guided Apple back to profitability through a number of tactics including introducing the iMac, iPod, iPhone and iPad to critical acclaim, launching the "Think different" campaign and other memorable advertising campaigns, opening the Apple Store retail chain, and acquiring numerous companies to broaden the company’s product portfolio. When Jobs resigned in 2011 for health reasons, and died two months later, he was succeeded as CEO by Tim Cook.

Apple became the first publicly traded U.S. company to be valued at over $1 trillion in August 2018, then at $2 trillion in August 2020, and at $3 trillion in January 2022. As of April 2023, it was valued at around $2.6 trillion. The company receives criticism regarding the labor practices of its contractors, its environmental practices, and its business ethics, including anti-competitive practices and materials sourcing. Nevertheless, the company has a large following and enjoys a high level of brand loyalty. It has also been consistently ranked as one of the world’s most valuable brands. 
'),

(5, 'Chevron Corporation', 'Energy', '/icons/companies/grey/chevron.svg', 'Chevron Corporation is an American multinational energy corporation predominantly in oil and gas. The second-largest direct descendant of Standard Oil, and originally known as the Standard Oil Company of California (shortened to Socal or CalSo), it is headquartered in San Ramon, California, and active in more than 180 countries. Within oil and gas, Chevron is vertical integrated and is involved in hydrocarbon exploration, production, refining, marketing and transport, chemicals manufacturing and sales, and power generation.

Chevron traces its history back to the 1870s to small California-based oil companies which were acquired by Standard and merged into Standard Oil of California. The company grew quickly on its own after the breakup of Standard Oil by continuing to acquire companies and partnering with others both inside and outside of California, eventually becoming one of the Seven Sisters that dominated the global petroleum industry from the mid-1940s to the 1970s. In 1985, Socal merged with the Pittsburgh-based Gulf Oil and rebranded as Chevron; the newly merged company later merged with Texaco in 2001. Today, Chevron manufactures and sells fuels, lubricants, additives, and petrochemicals, primarily in Western North America, the U.S. Gulf Coast, Southeast Asia, South Korea and Australia. In 2018, the company produced an average of 791,000 barrels of net oil-equivalent per day in United States.

Chevron is one of the largest companies in the world and the second largest oil company based in the United States by revenue, only behind fellow Standard Oil descendant ExxonMobil. Chevron ranked 16th on the Fortune 500 in 2022 with revenues of US$162.5 billion, which also ranked it 37th on the Fortune Global 500. The company is also the last-remaining oil and gas component of the Dow Jones Industrial Average since ExxonMobil’s exit from the index in 2020.

Chevron has been subject to numerous controversies arising out of its activities, the most notable of which being related to its activities and inherited liabilities from its acquisition of Texaco in the Lago Agrio oil field, which include allegations of both Chevron and Texaco collectively dumping 18 billion tons of toxic waste and spilling 17 million gallons of petroleum. Chevron and Texaco’s activities were the subject of a lawsuit Chevron lost to Ecuadorian residents defended in Ecuadorian court by Steven Donziger. Due to accusations of Donziger bribing the Ecuadorian court and the subsequent disbarment and criminal contempt charges against Donziger, Chevron was accused by environmentalists and human rights groups of jailing Donziger and compelling the US government to deny Donziger due process of law. 
'),

(6, 'Eli Lilly and Company', 'Health Care', '/icons/companies/grey/eli-lilly.svg', 'Eli Lilly and Company is an American pharmaceutical company headquartered in Indianapolis, Indiana, with offices in 18 countries. Its products are sold in approximately 125 countries. The company was founded in 1876 by, and named after, Colonel Eli Lilly, a pharmaceutical chemist and veteran of the American Civil War.

As of 2022, Lilly is known for its clinical depression drugs Prozac (fluoxetine) (1986), Cymbalta (duloxetine) (2004), and its antipsychotic medication Zyprexa (olanzapine) (1996), although its primary revenue drivers are the diabetes drugs Humalog (insulin lispro) (1996) and Trulicity (dulaglutide) (2014). Lilly’s achievements include being the first company to mass-produce the polio vaccine developed by Jonas Salk, and insulin. It was one of the first pharmaceutical companies to produce human insulin using recombinant DNA including Humulin (insulin medication), Humalog (insulin lispro), and the first approved biosimilar insulin product in the US, Basaglar (insulin glargine).

As of 1997, it was the largest corporation and the largest charitable benefactor in Indiana. In 2019, the company was ranked 123rd on the Fortune 500. It is ranked 221st on the Forbes Global 2000 list of the largest public companies in the world and 252nd on the Forbes list of America’s Best Employers. Lilly is a full member of the Pharmaceutical Research and Manufacturers of America and the European Federation of Pharmaceutical Industries and Associations (EFPIA). 
'),

(7, 'The Home Depot, Inc.', 'Consumer Discretionary', '/icons/companies/grey/home-depot.svg', 'The Home Depot, Inc., often simply referred to as Home Depot, is an American multinational home improvement retail corporation that sells tools, construction products, appliances, and services, including fuel and transportation rentals. Home Depot is the largest home improvement retailer in the United States. In 2021, the company had 490,600 employees and more than $151 billion in revenue. The company is headquartered in incorporated Cobb County, Georgia, with an Atlanta mailing address.

It operates many big-box format stores across the United States (including the District of Columbia, Guam, Puerto Rico and the U.S. Virgin Islands); all 10 provinces of Canada; and all 32 Mexican states and Mexico City. MRO company Interline Brands (now The Home Depot Pro) is also owned by The Home Depot, with 70 distribution centers across the United States. It has been involved in several controversies, primarily involving the security and safety of its consumers.

It is the sixth largest United States–based employer globally.
'),

(8, 'Johnson & Johnson (J&J)', 'Health Care', '/icons/companies/grey/johnson-johnson.svg', 'Johnson & Johnson (J&J) is an American multinational corporation founded in 1886 that develops medical devices, pharmaceuticals, and consumer packaged goods. Its common stock is a component of the Dow Jones Industrial Average, and the company is ranked No. 36 on the 2021 Fortune 500 list of the largest United States corporations by total revenue. Johnson & Johnson is one of the world’s most valuable companies, and is one of only two U.S.-based companies that has a prime credit rating of AAA, higher than that of the United States government.

Johnson & Johnson is headquartered in New Brunswick, New Jersey, the consumer division being located in Skillman, New Jersey. The corporation includes some 250 subsidiary companies with operations in 60 countries and products sold in over 175 countries. Johnson & Johnson had worldwide sales of $93.8 billion during the calendar year 2021.

Johnson & Johnson’s brands include numerous household names of medications and first aid supplies. Among its well-known consumer products are the Band-Aid Brand line of bandages, Tylenol medications, Johnson’s Baby products, Neutrogena skin and beauty products, Clean & Clear facial wash and Acuvue contact lenses. Johnson & Johnson’s pharmaceutical arm is Janssen Pharmaceuticals.

The company announced in November 2021 that it would split into two publicly traded companies: one focused on consumer products and the other on pharmaceuticals and medical technologies. 
'),

(9, 'Mastercard Inc.', 'Financials', '/icons/companies/grey/mastercard.svg', 'Mastercard Inc. (stylized as MasterCard from 1979–2016, mastercard from 2016–2019) is the second-largest payment-processing corporation worldwide. It offers a range of financial services. Its headquarters are in Purchase, New York. Throughout the world, its principal business is to process payments between the banks of merchants and the card-issuing banks or credit unions of the purchasers who use the Mastercard-brand debit, credit and prepaid cards to make purchases. Mastercard has been publicly traded since 2006.

Mastercard (originally Interbank then Master Charge) was created by an alliance of several banks and regional bankcard associations in response to the BankAmericard issued by Bank of America, which later became Visa, still its biggest competitor. Prior to its initial public offering, Mastercard Worldwide was a cooperative owned by the more than 25,000 financial institutions that issue its branded cards. 
'),

(10, 'McDonald’s Corporation', 'Consumer Discretionary', '/icons/companies/grey/mcdonalds.svg', 'McDonald’s Corporation is an American multinational fast food chain, founded in 1940 as a restaurant operated by Richard and Maurice McDonald, in San Bernardino, California, United States. They rechristened their business as a hamburger stand, and later turned the company into a franchise, with the Golden Arches logo being introduced in 1953 at a location in Phoenix, Arizona. In 1955, Ray Kroc, a businessman, joined the company as a franchise agent and proceeded to purchase the chain from the McDonald brothers. McDonald’s had its previous headquarters in Oak Brook, Illinois, but moved its global headquarters to Chicago in June 2018. McDonald’s is also a real estate company through its ownership of all restaurant locations.

McDonald’s is the world’s largest fast food restaurant chain, serving over 69 million customers daily in over 100 countries in more than 40,000 outlets as of 2021. McDonald’s is best known for its hamburgers, cheeseburgers and french fries, although their menu also includes other items like chicken, fish, fruit, and salads. Their best-selling licensed item are their french fries, followed by the Big Mac. The McDonald’s Corporation revenues come from the rent, royalties, and fees paid by the franchisees, as well as sales in company-operated restaurants. McDonald’s is the world’s second-largest private employer with 1.7 million employees (behind Walmart with 2.3 million employees). As of 2022, McDonald’s has the sixth-highest global brand valuation.

McDonald’s has been subject to criticism over the health effects of its products, its treatment of employees, and other business practices. 
'),

(11, 'Meta Platforms, Inc.', 'Information Technology', '/icons/companies/grey/meta.svg', 'Meta Platforms, Inc., formerly named Facebook, Inc., and TheFacebook, Inc., is an American multinational technology conglomerate based in Menlo Park, California. The company owns Facebook, Instagram, and WhatsApp, among other products and services. Meta is one of the world’s most valuable companies and among the ten largest publicly traded corporations in the United States. It is considered one of the Big Five American information technology companies, alongside Alphabet (Google), Amazon, Apple, and Microsoft.

Meta’s products and services include Facebook, Instagram, WhatsApp, Messenger, and Quest 2. It has acquired Reality Labs, Mapillary, CTRL-Labs, Kustomer, and has a 9.99% stake in Jio Platforms. In 2021, the company generated 97.5% of its revenue from the sale of advertising.

On October 28, 2021, the parent company of Facebook changed its name from Facebook, Inc., to Meta Platforms, Inc., to "reflect its focus on building the metaverse". According to Meta, the term "metaverse" refers to the integrated environment that links all of the company’s products and services. 
'),

(12, 'Microsoft Corporation', 'Information Technology', '/icons/companies/grey/microsoft-windows.svg', 'Microsoft Corporation is an American multinational technology corporation headquartered in Redmond, Washington. Microsoft’s best-known software products are the Windows line of operating systems, the Microsoft Office suite, and the Internet Explorer and Edge web browsers. Its flagship hardware products are the Xbox video game consoles and the Microsoft Surface lineup of touchscreen personal computers. Microsoft ranked No. 14 in the 2022 Fortune 500 rankings of the largest United States corporations by total revenue; it was the world’s largest software maker by revenue as of 2022. It is considered as one of the Big Five American information technology companies, alongside Alphabet (parent company of Google), Amazon, Apple, and Meta (formerly Facebook).

Microsoft was founded by Bill Gates and Paul Allen on April 4, 1975, to develop and sell BASIC interpreters for the Altair 8800. It rose to dominate the personal computer operating system market with MS-DOS in the mid-1980s, followed by Windows. The company’s 1986 initial public offering (IPO) and subsequent rise in its share price created three billionaires and an estimated 12,000 millionaires among Microsoft employees. Since the 1990s, it has increasingly diversified from the operating system market and has made a number of corporate acquisitions, their largest being the acquisition of LinkedIn for $26.2 billion in December 2016, followed by their acquisition of Skype Technologies for $8.5 billion in May 2011.

As of 2015, Microsoft is market-dominant in the IBM PC compatible operating system market and the office software suite market, although it has lost the majority of the overall operating system market to Android. The company also produces a wide range of other consumer and enterprise software for desktops, laptops, tabs, gadgets, and servers, including Internet search (with Bing), the digital services market (through MSN), mixed reality (HoloLens), cloud computing (Azure), and software development (Visual Studio).

Steve Ballmer replaced Gates as CEO in 2000 and later envisioned a "devices and services" strategy. This unfolded with Microsoft acquiring Danger Inc. in 2008, entering the personal computer production market for the first time in June 2012 with the launch of the Microsoft Surface line of tablet computers, and later forming Microsoft Mobile through the acquisition of Nokia’s devices and services division. Since Satya Nadella took over as CEO in 2014, the company has scaled back on hardware and instead focused on cloud computing, a move that helped the company’s shares reach their highest value since December 1999.

Earlier dethroned by Apple in 2010, in 2018, Microsoft reclaimed its position as the most valuable publicly traded company in the world. In April 2019, Microsoft reached a trillion-dollar market cap, becoming the third U.S. public company to be valued at over $1 trillion after Apple and Amazon, respectively. As of 2022, Microsoft has the fourth-highest global brand valuation.

Microsoft has been criticized for its monopolistic practices and the company’s software has been criticized for problems with ease of use, robustness, and security. 
'),

(13, 'Nvidia Corporation', 'Information Technology', '/icons/companies/grey/nvidia.svg', 'Nvidia Corporation (/ɛnˈvɪdiə/ en-VID-ee-ə) is an American multinational technology company incorporated in Delaware and based in Santa Clara, California. It is a software and fabless company which designs graphics processing units (GPUs), application programming interface (APIs) for data science and high-performance computing as well as system on a chip units (SoCs) for the mobile computing and automotive market. Nvidia is a dominant supplier of artificial intelligence hardware and software. Its professional line of GPUs are used in workstations for applications in such fields as architecture, engineering and construction, media and entertainment, automotive, scientific research, and manufacturing design.

In addition to GPU manufacturing, Nvidia provides an API called CUDA that allows the creation of massively parallel programs which utilize GPUs. They are deployed in supercomputing sites around the world. More recently, it has moved into the mobile computing market, where it produces Tegra mobile processors for smartphones and tablets as well as vehicle navigation and entertainment systems. In addition to AMD, its competitors include Intel, Qualcomm and AI-accelerator companies such as Graphcore. It also makes AI-powered software for audio and video processing, e.g. Nvidia Maxine.

Nvidia’s GPUs are used for edge to cloud computing and supercomputers. Nvidia expanded its presence in the gaming industry with its handheld game consoles Shield Portable, Shield Tablet, and Shield TV and its cloud gaming service GeForce Now.

Nvidia’s offer to acquire Arm from SoftBank in September 2020 failed to materialize following extended regulatory scrutiny, leading to the termination of the deal in February 2022 in what would have been the largest semiconductor acquisition. 
'),

(14, 'The Proctore & Gamble Company (P&G)', 'Consumer Non-Durables', '/icons/companies/grey/procter-gamble.svg', 'The Procter & Gamble Company (P&G) is an American multinational consumer goods corporation headquartered in Cincinnati, Ohio, founded in 1837 by William Procter and James Gamble. It specializes in a wide range of personal health/consumer health, personal care and hygiene products; these products are organized into several segments including beauty; grooming; health care; fabric and home care; and baby, feminine, and family care. Before the sale of Pringles to Kellogg’s, its product portfolio also included food, snacks, and beverages. P&G is incorporated in Ohio.

In 2014, P&G recorded $83.1 billion in sales. On August 1, 2014, P&G announced it was streamlining the company, dropping and selling off around 100 brands from its product portfolio in order to focus on the remaining 65 brands, which produced 95% of the company’s profits. A.G. Lafley, the company’s chairman and CEO until October 2015, said the future P&G would be "a much simpler, much less complex company of leading brands that’s easier to manage and operate".

Jon Moeller is the current president and CEO of P&G. 
'),

(15, 'Tesla, Inc.', 'Information Technology', '/icons/companies/grey/tesla-motors.svg', 'Tesla, Inc. (/ˈtɛslə/ TESS-lə or /ˈtɛzlə/ TEZ-lə) is an American multinational automotive and clean energy company headquartered in Austin, Texas. Tesla designs and manufactures electric vehicles (electric cars and trucks), battery energy storage from home to grid-scale, solar panels and solar roof tiles, and related products and services. Tesla is one of the world’s most valuable companies and, as of 2023, is the world’s most valuable automaker. In 2022, the company had the most worldwide sales of battery electric vehicles, capturing 18% of the market. Through its subsidiary Tesla Energy, the company develops and is a major installer of photovoltaic systems in the United States. Tesla Energy is also one of the largest global suppliers of battery energy storage systems, with 6.5 gigawatt-hours (GWh) installed in 2022.

Tesla was incorporated in July 2003 by Martin Eberhard and Marc Tarpenning as Tesla Motors. The company’s name is a tribute to inventor and electrical engineer Nikola Tesla. In February 2004, via a $6.5 million investment, Elon Musk became the largest shareholder of the company. He has served as CEO since 2008. According to Musk, the purpose of Tesla is to help expedite the move to sustainable transport and energy, obtained through electric vehicles and solar power. Tesla began production of its first car model, the Roadster sports car, in 2008. This was followed by the Model S sedan in 2012, the Model X SUV in 2015, the Model 3 sedan in 2017, the Model Y crossover in 2020, and the Tesla Semi truck in 2022. The company plans production of the Cybertruck light-duty pickup truck in 2023. The Model 3 is the all-time bestselling plug-in electric car worldwide, and in June 2021 became the first electric car to sell 1 million units globally. Tesla’s 2022 full year deliveries were around 1.31 million vehicles, a 40% increase over the previous year, and cumulative sales totaled 3 million cars as of August 2022. In October 2021, Tesla’s market capitalization reached $1 trillion, the sixth company to do so in U.S. history.

Tesla has been the subject of several lawsuits, government scrutiny, journalistic criticism, and public controversies arising from statements and acts of CEO Elon Musk and from allegations of whistleblower retaliation, worker rights violations, and defects with their products. 
'),

(16, 'Visa Inc.', 'Financials', '/icons/companies/grey/visa.svg', 'Visa Inc. (/ˈviːzə, ˈviːsə/; stylized as VISA) is an American multinational financial services corporation headquartered in San Francisco, California. It facilitates electronic funds transfers throughout the world, most commonly through Visa-branded credit cards, debit cards and prepaid cards. Visa is one of the world’s most valuable companies.

Visa does not issue cards, extend credit or set rates and fees for consumers; rather, Visa provides financial institutions with Visa-branded payment products that they then use to offer credit, debit, prepaid and cash access programs to their customers. In 2015, the Nilson Report, a publication that tracks the credit card industry, found that Visa’s global network (known as VisaNet) processed 100 billion transactions during 2014 with a total volume of US$6.8 trillion.

Visa was founded in 1958 by Bank of America (BofA) as the BankAmericard credit card program. In response to competitor Master Charge (now Mastercard), BofA began to license the BankAmericard program to other financial institutions in 1966. By 1970, BofA gave up direct control of the BankAmericard program, forming a cooperative with the other various BankAmericard issuer banks to take over its management. It was then renamed Visa in 1976.

Nearly all Visa transactions worldwide are processed through the company’s directly operated VisaNet at one of four secure data centers, located in Ashburn, Virginia; Highlands Ranch, Colorado; London, England; and Singapore. These facilities are heavily secured against natural disasters, crime, and terrorism; can operate independently of each other and from external utilities if necessary; and can handle up to 30,000 simultaneous transactions and up to 100 billion computations every second.

Visa is the world’s second-largest card payment organization (debit and credit cards combined), after being surpassed by China UnionPay in 2015, based on annual value of card payments transacted and number of issued cards. However, because UnionPay’s size is based primarily on the size of its domestic market in China, Visa is still considered the dominant bankcard company in the rest of the world, where it commands a 50% market share of total card payments. 
'),

(17, 'Walmart Inc.', 'Retail', '/icons/companies/grey/walmart.svg', 'Walmart Inc. ( /ˈwɔːlmɑːrt/; formerly Wal-Mart Stores, Inc.) is an American multinational retail corporation that operates a chain of hypermarkets (also called supercenters), discount department stores, and grocery stores in the United States, headquartered in Bentonville, Arkansas. The company was founded by brothers Sam and James "Bud" Walton in nearby Rogers, Arkansas in 1962 and incorporated under Delaware General Corporation Law on October 31, 1969. It also owns and operates Sam’s Club retail warehouses.

As of October 31, 2022, Walmart has 10,586 stores and clubs in 24 countries, operating under 46 different names. The company operates under the name Walmart in the United States and Canada, as Walmart de México y Centroamérica in Mexico and Central America, and as Flipkart Wholesale in India. It has wholly owned operations in Chile, Canada, and South Africa. Since August 2018, Walmart held only a minority stake in Walmart Brasil, which was renamed Grupo Big in August 2019, with 20 percent of the company’s shares, and private equity firm Advent International holding 80 percent ownership of the company. They eventually divested their shareholdings in Grupo Big to French retailer Carrefour, in transaction worth R$7 billion and completed on June 7, 2022.

Walmart is the world’s largest company by revenue, with about US$570 billion in annual revenue, according to the Fortune Global 500 list in October 2022. It is also the largest private employer in the world with 2.2 million employees. It is a publicly traded family-owned business, as the company is controlled by the Walton family. Sam Walton’s heirs own over 50 percent of Walmart through both their holding company Walton Enterprises and their individual holdings. Walmart was the largest United States grocery retailer in 2019, and 65 percent of Walmart’s US$510.329 billion sales came from U.S. operations.

Walmart was listed on the New York Stock Exchange in 1972. By 1988, it was the most profitable retailer in the U.S., and it had become the largest in terms of revenue by October 1989. The company was originally geographically limited to the South and lower Midwest, but it had stores from coast to coast by the early 1990s. Sam’s Club opened in New Jersey in November 1989, and the first California outlet opened in Lancaster, in July 1990. A Walmart in York, Pennsylvania, opened in October 1990, the first main store in the Northeast.

Walmart’s investments outside the U.S. have seen mixed results. Its operations and subsidiaries in Canada, the United Kingdom (ASDA), Central America, South America, and China are successful, but its ventures failed in Germany, Japan, South Korea and Argentina. 
');
